« En tant qu’administrateur de la plateforme pour mon établissement, je mets à disposition l’ensemble des outils communs des agents INRAE en quelques minutes. »
Marc https://matrix.agent.externe.tchap.gouv.fr/_matrix/media_proxy/unstable/thumbnail/agent.agriculture.tchap.gouv.fr/gBGWYlsGApOFHSBuYedsvWQM?width=448&height=448&method=scale
« En tant qu’utilisateur, je me sers de SNAP dès le démarrage de mon navigateur Internet et j’ai sous la main tous les signets utiles à ma fonction. Dès que je souhaite en ajouté un, un simple copier/coller dans mon espace personnel et c’est terminé !! »

« Voilà, nous avons enfin trouvé le « chainon manquant » qui facilitera l’intégration d’un nouveau collaborateur dans mon service… Toutes les applications utiles sous la main en quelques secondes !!! »

