import Head from 'next/head'
import { Inter } from '@next/font/google'
import { Hero } from '@/components/Hero.section'
import { Mission } from '@/components/Mission.section'
import { ImpactServices } from '@/components/ImpactServices.section'
import { Testimonials } from '@/components/Testimonials.section'
import WriteUs from '@/components/WriteUs.section'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>La Suite Numérique</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Hero />
      <Mission />
      <ImpactServices />
      <Testimonials />
      <WriteUs />
    </>
  )
}
